language: java

install: mvn install -DskipTests=true -DfinalName=stallone -PbuildDistribution
# skip tests
script: true

after_success: 
  - ls -alh target/

deploy:
  provider: releases
  api-key:
  file: stallone-jar-with-dependencies-proguard.jar 
  on:
    tags: true
    all_branches: true
