language: java

before_install: mvn install -DskipTests=true -DfinalName=stallone -PbuildDistribution
# skip tests
script: true

deploy:
  provider: releases
  api-key:
  file: stallone-jar-with-dependencies-proguard.jar 
  on:
    tags: true
    all_branches: true
