/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stallone.api.dataprocessing;

/**
 *
 * @author noe
 */
public interface IDataProcessor
{
    /**
     * Adds another data processor as input that sends data to this processor.
     * @param sender 
     */
    public void addSender(IDataProcessor sender);
    
    /**
     * Adds another data processor as receiver for the data generated by this 
     * processor.
     * @param receiver 
     */
    public void addReceiver(IDataProcessor receiver);
    
    /**
     * Called before run(). Read/prepare inputs and setup for main action.
     */
    public void init();
    
    /**
     * Perform the main action (e.g. run an estimator, write data, etc).
     */
    public void run();
    
    /**
     * Called at the end. cleanup all data. Must init() again to restart.
     */
    public void cleanup();
}
